server:
  port: 8082

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/joseniquen/config-server
 #           searchPaths: config-data
#          default-label: master
          username: ${GITUSER}
          password: ${GITPASS}

          searchPaths: config-data-main
#          clone-on-start: true 
#        git:
#          uri: https://github.com/arodriguezcu/Proyecto3-everis.git
#          searchPaths: config-data
#          default-label: main