server:
  port: 8082

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joseniquen/config-server
          searchPaths: config-data
#          default-label: master
#          username: ${GITUSER}
#          password: ${GITPASS}
          default-label: main
#          clone-on-start: true 
#        git:
#          uri: https://github.com/arodriguezcu/Proyecto3-everis.git
#          searchPaths: config-data
#          default-label: main