server:
  port: 8081

spring:
    application:
        name: account-microservice
    data:
        mongodb:
            host: localhost
            port: 27017
            database: BankCustomer

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9999/eureka/
