server:
  port: 8081

spring:
    application:
        name: account-microservice
    data:
        mongodb:
            uri: mongodb://mongodb:27017/BankAccount 

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:9999/eureka/
