server:
  port: 8081

spring:
    application:
        name: account-microservice
    data:
        mongodb:
            uri: mongodb://locahost:27017/

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9999/eureka/
