server:
  port: 8090
  
spring:
  application:
    name: representative
  data:
    mongodb:
      uri: mongodb://localhost:27017/ProyectBootcamp1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/