server:
    port: 9999

eureka:
    server:
        enableSelfPreservation: false
    instance:
        hostname: localhost
        preferIpAddress: true
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
